name: ci

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: shfmt
        if: matrix.os == 'macOS-latest'
        run: |
          brew install shfmt shellcheck
          shfmt -d install.sh

      - name: test shell
        if: matrix.os != 'windows-latest'
        shell: bash
        run: ./test/install_test.sh

      - name: test powershell core
        shell: pwsh
        run: ./test/install_test.ps1

      - name: test windows powershell
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: ./test/install_test.ps1
